//! Build script for the `cori` binary.
//!
//! Phase 8 — embeds two file trees into the binary:
//!
//! 1. `skill/` — the Cori agent skill, extracted by
//!    `cori skill install --agent <name>` to the agent's local skill
//!    directory.
//! 2. `examples/hello_world/` — the runbook used by `cori demo`,
//!    extracted to `~/.cori/runbooks/hello_world/` on first run.
//!
//! For each tree we walk the directory and generate a Rust slice of
//! `(relative_path, &'static [u8])` tuples written to `$OUT_DIR`. The
//! emitted modules are picked up by `src/embedded.rs` via `include!`.
//! Storing the file contents directly (rather than a tarball) keeps the
//! decompression path zero-dep and lets `include_bytes!` deduplicate
//! identical assets across builds.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    // `crates/cori-cli/` → repo root
    let repo_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("cori-cli should live at <repo>/crates/cori-cli")
        .to_path_buf();

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    emit_tree(
        &repo_root.join("skill"),
        &out_dir.join("skill_files.rs"),
        "SKILL_FILES",
    );
    emit_tree(
        &repo_root.join("examples").join("hello_world"),
        &out_dir.join("hello_world_files.rs"),
        "HELLO_WORLD_FILES",
    );
}

fn emit_tree(root: &Path, out_file: &Path, const_name: &str) {
    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    walk(root, root, &mut entries);
    // Deterministic order — keeps the generated file stable across builds.
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut src = String::new();
    src.push_str("// @generated by build.rs — do not edit\n");
    src.push_str(&format!("pub static {const_name}: &[(&str, &[u8])] = &[\n"));
    for (rel, abs) in &entries {
        // Re-run the build if any embedded file changes.
        println!("cargo:rerun-if-changed={}", abs.display());
        // Rust string literal escape for the relative path. Since these
        // come from filesystem walks we only need to escape `\` and `"`.
        let rel_escaped = rel.replace('\\', "\\\\").replace('"', "\\\"");
        let abs_str = abs.to_string_lossy().replace('\\', "\\\\");
        src.push_str(&format!(
            "    (\"{rel_escaped}\", include_bytes!(\"{abs_str}\")),\n"
        ));
    }
    src.push_str("];\n");

    fs::write(out_file, src).expect("writing embedded file table");

    // Also re-run when the root itself appears/disappears.
    println!("cargo:rerun-if-changed={}", root.display());
}

fn walk(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let read = match fs::read_dir(dir) {
        Ok(r) => r,
        // Missing root — emit an empty table rather than failing the build,
        // so contributors who delete `examples/hello_world/` still get a
        // useful compiler error rather than a cryptic build-script panic.
        Err(_) => return,
    };
    for entry in read.flatten() {
        let path = entry.path();
        let name = entry.file_name();
        let name_str = name.to_string_lossy();
        // Skip OS / editor cruft and any hidden dotfiles.
        if name_str.starts_with('.') || name_str == "node_modules" || name_str == "target" {
            continue;
        }
        let file_type = match entry.file_type() {
            Ok(t) => t,
            Err(_) => continue,
        };
        if file_type.is_dir() {
            walk(root, &path, out);
        } else if file_type.is_file() {
            let rel = path
                .strip_prefix(root)
                .expect("walk produced a path outside root")
                .to_string_lossy()
                // Normalise Windows separators so the embedded table is
                // platform-independent.
                .replace('\\', "/");
            out.push((rel, path));
        }
    }
}
